services:
  - type: web
    name: skillshare-backend
    runtime: node
    rootDir: my-gemini-backend
    startCommand: node server.js
    buildCommand: npm install
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production